<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260314002837 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE resultat_laboratoire_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, demande VARCHAR(255) NOT NULL, resultat TEXT DEFAULT NULL, valeur_normale TEXT DEFAULT NULL, ordre INT NOT NULL, resultat_laboratoire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A50CC6D7EC71C459 ON resultat_laboratoire_ligne (resultat_laboratoire_id)');
        $this->addSql('ALTER TABLE resultat_laboratoire_ligne ADD CONSTRAINT FK_A50CC6D7EC71C459 FOREIGN KEY (resultat_laboratoire_id) REFERENCES resultat_laboratoire (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE resultat_laboratoire_ligne DROP CONSTRAINT FK_A50CC6D7EC71C459');
        $this->addSql('DROP TABLE resultat_laboratoire_ligne');
    }
}
