<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260313165901 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE resultat_laboratoire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, resultat TEXT DEFAULT NULL, conclusion TEXT DEFAULT NULL, date_validation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valide_par VARCHAR(150) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, prescription_prestation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_743224F5FD5FB388 ON resultat_laboratoire (prescription_prestation_id)');
        $this->addSql('ALTER TABLE resultat_laboratoire ADD CONSTRAINT FK_743224F5FD5FB388 FOREIGN KEY (prescription_prestation_id) REFERENCES prescription_prestation (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE resultat_laboratoire DROP CONSTRAINT FK_743224F5FD5FB388');
        $this->addSql('DROP TABLE resultat_laboratoire');
    }
}
